import type { Metadata } from "next";
import {Roboto_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Cart from "./components/Providers";
import ShoppingCart from "./components/ShoppingCart";

const inter = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
          <Cart>
            <Navbar />
            <ShoppingCart />
            {children}
          </Cart>
      </body>
    </html>
  );
}
